fix sonarcloud errors
I-Lima/Mandacaru-Broker-API pull request #28
Opened 2024-03-14 16:57 UTC by moisesocosta

- Defining a constant instead of duplicating
- Add the mandatory size restriction.
- Removing unused imports

2024-03-14 17:16 UTC, I-Lima requested changes

2024-03-14 17:16 UTC, I-Lima commented on src/main/java/com/mandacarubroker/controller/UsersController.java
> +              INTERNAL_SERVER_ERROR_MESSAGE,
Essa substituição esta da mensagem está no local errado, retorne a mensagem anterior.

2024-03-15 12:57 UTC, moisesocosta commented on src/main/java/com/mandacarubroker/controller/UsersController.java
> +              INTERNAL_SERVER_ERROR_MESSAGE,
Opa, verdade. Acabei confundindo

2024-03-15 16:16 UTC, I-Lima approved these changes

2024-03-15 16:17 UTC, merged